name: build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
    - name: Run Metanorma Ubuntu install script
      env:
        JAVA_OPTS: java.awt.headless=true
      run: |
        sudo -H ./ubuntu.sh
        which plantuml latexml xml2rfc idnits
    - name: Install gems
      run: |
        sudo -H env USE_RVM=false ./install-gems.sh
        which metanorma
    - name: Run Puppeteer install script
      run: |
        ./ubuntu-install-puppeteer.sh
        npm -g ls puppeteer